---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks
#
- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/murrykane/Ansible
    - ChatGBT:
        - abbr: GH
          href: https://chat.openai.com/
          
- Social:
    - Linkedin:
        - abbr: lk
          href: https://www.linkedin.com/
#
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
#
- Purchasing:
  - Amazon:
    - abbr: AZ 
      href: https://amazon.com