#version: '3'

services:
  portainer-prod-1:
    image: portainer/portainer-ce
    container_name: portainer-prod-1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 9001:9000
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/murry/containers/portainer-prod-1/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-prod-1.entrypoints=http"
      - "traefik.http.routers.portainer-prod-1.rule=Host(`portainer-prod-1.local.kaneworld.org`)"
      - "traefik.http.middlewares.portainer-prod-1-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer-prod-1.middlewares=portainer-prod-1-https-redirect"
      - "traefik.http.routers.portainer-prod-1-secure.entrypoints=https"
      - "traefik.http.routers.portainer-prod-1-secure.rule=Host(`portainer-prod-1.local.kaneworld.org`)"
      - "traefik.http.routers.portainer-prod-1-secure.tls=true"
      - "traefik.http.routers.portainer-prod-1-secure.service=portainer-prod-1"
      - "traefik.http.services.portainer-prod-1.loadbalancer.server.port=9000"
      # for authentik
      # - "traefik.http.routers.portainer-prod-1-callback.rule=Host(`portainer-prod-1.local.kaneworld.org`) && PathPrefix(`/oauth2/callback`)"
      # - "traefik.http.routers.portainer-prod-1-callback.entrypoints=https"
      # - "traefik.http.routers.portainer-prod-1-callback.tls=true"
      # #- "traefik.http.routers.portainer-prod-1-callback.tls.certresolver=myresolver"
      # - "traefik.http.services.portainer-prod-1-callback.loadbalancer.server.port=9000" 
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
