services:
  cloudflared-prod-1:
    container_name: cloudflared-prod-1
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    hostname: cloudflared
    #user: root
    environment:
      - NO_AUTOUPDATE=true
      - TUNNEL_TOKEN=$TUNNEL_TOKEN 
    command: 'tunnel --no-autoupdate run'
    networks:
      # - cloudflare-net
      - proxy

networks:
  # cloudflare-net:
  #   driver: bridge
  proxy:
    external: true