---
server:
  http_listen_port: 9080
  log_level: "info"
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  #- url: http://loki-prod-4:3100/loki/api/v1/push
  - url: https://loki-prod-4.local.kaneworld.org/loki/api/v1/push
    tenant_id: ""
    batchsize: 1048576  # 1MB
    timeout: 10s
    # backoff_config:
    #   min_backoff: 500ms
    #   max_backoff: 10s   # Adjust the backoff times to prevent flooding
    #   max_retries: 10    # Adjust the number of retries before giving up

scrape_configs:

  - job_name: varlogs-cyborg
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs-cyborg
        __path__: /var/log/**/*.log

    pipeline_stages:
      - match:
          selector: '{job="varlogs-cyborg"}'
          stages:
            # Extract filename from path
            - regex:
                #expression: '/var/log/(?P<filename>[^/]+)'
                expression: '.*/(?P<filename>[^/]+\.log)$'
            - labels:
                filename:

            # Extract raw log level
            - regex:
                expression: '(?i)(?P<level>INFO|ERROR|WARN|WARNING|DEBUG|TRACE|FATAL|NOTE)'  # case-insensitive
            - labels:
                level:

            # Normalize level to uppercase
            - replace:
                expression: '(?i)(info|error|warn|warning|debug|trace|fatal|note)'
                replace: '${1^^}'   # `${1^^}` uppercases the match in Go template syntax
                source: level

  - job_name: journal
    journal:
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'host'
      - source_labels: ['__journal__hostname']
        target_label: 'server'
      - source_labels: ['__journal__pid']
        target_label: 'pid'
      - source_labels: ['__journal__exe']
        target_label: 'exe'
      - source_labels: ['__journal__comm']
        target_label: 'comm'
      - source_labels: ['__journal__uid']
        target_label: 'uid'
      - source_labels: ['__journal__gid']
        target_label: 'gid'
      - source_labels: ['__journal__transport']
        target_label: 'transport'