# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: kaneworld # change to your domain
#   namespace: default # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
# spec:
#   secretName: kaneworld-tls # change to your secretname
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer
#   commonName: "*.kaneworld.org" # change to your domain
#   dnsNames:
#   - "*.kaneworld.org" # change to your domain
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-kaneworld
  namespace: default
spec:
  secretName: local-kaneworld-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.local.kaneworld.org"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-kaneworld
  namespace: traefik
spec:
  secretName: local-kaneworld-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.local.kaneworld.org"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-kaneworld
  namespace: pihole
spec:
  secretName: local-kaneworld-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.local.kaneworld.org"


# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: kaneworld
#   namespace: pihole
# spec:
#   secretName: kaneworld-tls
#   commonName: 'local.kaneworld.org'
#   dnsNames:
#   - "*.local.kaneworld.org" # change to your domain
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer
