#version: '3'
# make sure ${HOME}/containers/traefik/acme.json   is root owned and 600 permissions
# 
secrets:
  cf-token:
    file: ./cf-token
services:
  traefik-prod-3:
    image: traefik:latest # or traefik:v3.3 to pin a version
    container_name: traefik-prod-3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true # helps to increase security
    secrets:
      - cf-token # the secret at the top of this file
    env_file:
      - .env # store other secrets e.g., dashboard password
    networks:
       proxy:
    ports:
      - 80:80
      - 443:443
      - 8899:8899
     # - 10000:10000 # optional
     # - 33073:33073 # optional
    environment:
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      # - CF_API_EMAIL=your@email.com # Cloudflare email
      # - CF_DNS_API_TOKEN=YOUR-TOKEN # Cloudflare API Token
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf-token # see https://doc.traefik.io/traefik/https/acme/#providers
      # token file is the proper way to do it
      - TRAEFIK_NODE_NAME=${TRAEFIK_NODE_NAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/murry/containers/traefik-prod-3/data/traefik.yml:/traefik.yml:ro
      - /home/murry/containers/traefik-prod-3/data/acme.json:/acme.json
      - /home/murry/containers/traefik-prod-3/data/config.yml:/config.yml:ro
      #- /home/murry/containers/traefik-prod-3/logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-prod-3.entrypoints=http"
      - "traefik.http.routers.traefik-prod-3.rule=Host(`traefik-prod-3.local.kaneworld.org`)"
      - "traefik.http.middlewares.traefik-prod-3-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-prod-3-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik-prod-3.middlewares=traefik-prod-3-https-redirect"
      - "traefik.http.routers.traefik-prod-3-secure.entrypoints=https"
      - "traefik.http.routers.traefik-prod-3-secure.rule=Host(`traefik-prod-3.local.kaneworld.org`)"
      - "traefik.http.routers.traefik-prod-3-secure.middlewares=traefik-prod-3-auth"
      - "traefik.http.routers.traefik-prod-3-secure.tls=true"
      #for authentik auth
      - "traefik.http.routers.traefik-prod-3-secure.middlewares=auth-forwardauth@file"
      - "traefik.http.routers.traefik-prod-3-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-prod-3-secure.tls.domains[0].main=local.kaneworld.org"
      - "traefik.http.routers.traefik-prod-3-secure.tls.domains[0].sans=*.local.kaneworld.org"
      - "traefik.http.routers.traefik-prod-3-secure.service=api@internal"
      # Unauthenticated API-only route for Homepage widget
      - "traefik.http.routers.traefik-api.rule=Host(`traefik3-widget.local.kaneworld.org`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.entrypoints=https"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-api.tls.certresolver=cloudflare"
      # for metrics
      - "traefik.http.routers.traefik-metrics.rule=Host(`traefik3-metrics.local.kaneworld.org`) && Path(`/metrics`)"
      #- "traefik.http.routers.traefik-metrics.entrypoints=metrics"  #over tls with certificate...... so switched to 443/https
      - "traefik.http.routers.traefik-metrics.entrypoints=https"
      - "traefik.http.routers.traefik-metrics.tls=true"
      - "traefik.http.routers.traefik-metrics.service=prometheus@internal"
  # crowdsec-error-pages:
  #   image: nginx:alpine
  #   container_name: crowdsec-error-pages
  #   volumes:
  #     - ./error-pages:/usr/share/nginx/html:ro
  #   restart: unless-stopped
  #   networks:
  #     proxy:
networks:
  proxy:
    external: true # or comment this line to auto create the network


