services:
  # Vaultwarden Password Manager
  vaultwarden-prod-1:
    image: vaultwarden/server:latest
    container_name: vaultwarden-prod-1
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    ports:
      - 8035:80
    networks:
      - proxy
    environment:
      # This is required to allow vaultwarden to verify the TLS certificate!
      #- DOMAIN=https://vault.$DOMAINNAME_HS
      DOMAIN: ${DOMAIN}
      # Vaultwarden SMTP settings
      SMTP_HOST: ${SMTP_HOST}                 # SMTP server address (e.g., smtp.gmail.com for Gmail)
      SMTP_PORT: ${SMTP_PORT}                 # Port for STARTTLS (587)
      SMTP_ENCRYPTION: ${SMTP_ENCRYPTION}     # Use STARTTLS for port 587 or SSL/TLS for 465
      SMTP_USERNAME: ${SMTP_USERNAME}         # Your Gmail email address
      SMTP_PASSWORD: ${SMTP_PASSWORD}         # Use an app-specific password if 2FA is enabled
      SMTP_FROM: ${SMTP_FROM}                 # The "from" email address Vaultwarden will use
      # Optional Vaultwarden settings
      #WEBSOCKET_ENABLED: "true"
      #DATABASE_URL: "sqlite:////data/db.sqlite3"  # SQLite database path
      SSO_ENABLED: ${SSO_ENABLED}
      SSO_AUTHORITY: ${SSO_AUTHORITY}
      SSO_CLIENT_ID: ${SSO_CLIENT_ID}
      SSO_CLIENT_SECRET: ${SSO_CLIENT_SECRET}
      SSO_SCOPES: ${SSO_SCOPES}
      SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: ${SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION}
      SSO_CLIENT_CACHE_EXPIRATION: ${SSO_CLIENT_CACHE_EXPIRATION}
      SSO_ONLY: ${SSO_ONLY}
      SSO_SIGNUPS_MATCH_EMAIL: ${SSO_SIGNUPS_MATCH_EMAIL}
    volumes:
      #- $DOCKERDIR/appdata/vaultwarden/data:/data
      - /home/murry/containers/vaultwarden-prod-1/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden-prod-1.entrypoints=http"
      - "traefik.http.routers.vaultwarden-prod-1.rule=Host(`vaultwarden-prod-1.local.kaneworld.org`)"
      - "traefik.http.routers.vaultwarden-prod-1.middlewares=default-whitelist@file"
      - "traefik.http.middlewares.vaultwarden-prod-1-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vaultwarden-prod-1.middlewares=vaultwarden-prod-1-https-redirect"
      - "traefik.http.routers.vaultwarden-prod-1-secure.entrypoints=https"
      - "traefik.http.routers.vaultwarden-prod-1-secure.rule=Host(`vaultwarden-prod-1.local.kaneworld.org`)"
      - "traefik.http.routers.vaultwarden-prod-1-secure.tls=true"
      - "traefik.http.routers.vaultwarden-prod-1-secure.service=vaultwarden-prod-1"
      - "traefik.http.services.vaultwarden-prod-1.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true