
services:
  portainer-prod-4:
    image: portainer/portainer-ce
    container_name: portainer-prod-4
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 9001:9000
      - 8001:8001
      - 9444:9443
    # networks:
    #   - portainer_default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-prod-4.entrypoints=http"
      - "traefik.http.routers.portainer-prod-4.rule=Host(`portainer-prod-4.local.kaneworld.org`)"
      - "traefik.http.middlewares.portainer-prod-4-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer-prod-4.middlewares=portainer-prod-4-https-redirect"
      - "traefik.http.routers.portainer-prod-4-secure.entrypoints=https"
      - "traefik.http.routers.portainer-prod-4-secure.rule=Host(`portainer-prod-4.local.kaneworld.org`)"
      - "traefik.http.routers.portainer-prod-4-secure.tls=true"
      - "traefik.http.routers.portainer-prod-4-secure.service=portainer-prod-4"
      - "traefik.http.services.portainer-prod-4.loadbalancer.server.port=9000"
      # # for authentik
      - "traefik.http.routers.portainer-prod-4-callback.rule=Host(`portainer-prod-4.local.kaneworld.org`) && PathPrefix(`/oauth2/callback`)"
      - "traefik.http.routers.portainer-prod-4-callback.entrypoints=https"
      - "traefik.http.routers.portainer-prod-4-callback.tls=true"
      #- "traefik.http.routers.portainer-prod-4-callback.tls.certresolver=myresolver"
      - "traefik.http.services.portainer-prod-4-callback.loadbalancer.server.port=9000" 
      - "traefik.docker.network=proxy"

networks:
  portainer_default:
    external: true
