# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  # body_size_limit: 40MB
  # sample_limit: 8500
  # target_limit: 30
  # label_limit: 30
  # label_name_length_limit: 200
  # label_value_length_limit: 200
  # scrape_timeout: 14s
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager-prod-1:9093' ]

rule_files:
  - alerts.yml

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # # metrics_path defaults to '/metrics'
    # # scheme defaults to 'http'.
    # scheme: https
    # tls_config:
    #   ca_file: /etc/prometheus/prometheus.kane.com.crt
    static_configs:
      - targets: ["mkserver.kane.mk:9090"]

  - job_name: 'unifipoller'
    scrape_interval: 30s
    static_configs:
      - targets: ['mkserver.kane.mk:9130']

  - job_name: 'MurryPC'
    scrape_interval: 30s
    static_configs:
    - targets: ['murrypc.kane.mk:9182']

  - job_name: 'Router NodeExporter'
    scrape_interval: 30s
    static_configs:
    - targets: ['router.kane.mk:9100']

  - job_name: 'pve-kanecluster'
    static_configs:
      - targets:
        - 192.168.1.15  # Proxmox VE node 1 (coco)
        #- 192.168.1.10 # Proxmox VE node 2 (mini)
        #- 192.168.1.9  # Proxmox VE node 3 (nvidia)
    metrics_path: /pve
    params:
      module: [kanecluster]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.234:9221

  - job_name: 'traefik-mkserver'
    scrape_interval: 30s
    static_configs:
      - targets: ["traefik1-metrics.local.kaneworld.org"]

  - job_name: 'traefik-cyborg'
    scrape_interval: 30s
    static_configs:
      - targets: ["traefik3-metrics.local.kaneworld.org"]

  - job_name: 'TraeFik Raptor'
    scrape_interval: 30s
    static_configs:
      - targets: ["traefik4-metrics.local.kaneworld.org"]     

  - job_name: 'TraeFik Unraid'
    scrape_interval: 30s
    static_configs:
      - targets: ["traefik5-metrics.local.kaneworld.org"]     

  - job_name: 'TraeFik Auth'
    scrape_interval: 30s
    static_configs:
      - targets: ["traefik6-metrics.local.kaneworld.org"]     

  - job_name: 'TraeFik MurDogNAS'
    scrape_interval: 30s
    static_configs:
      - targets: ["traefik7-metrics.local.kaneworld.org"]     

  - job_name: 'TraeFik Docker-Ceph'
    scrape_interval: 30s
    static_configs:
      - targets: ["traefik8-metrics.local.kaneworld.org"]     

  - job_name: 'TraeFik Docker-Dev'
    scrape_interval: 30s
    static_configs:
      - targets: ["tk-dev-1-metrics.local.kaneworld.org"]     


  - job_name: "loki-prod-4"
    scrape_interval: 30s
    static_configs:
      - targets: ["loki-prod-4.local.kaneworld.org"]

  - job_name: 'SpeedTest Ookala'
    scrape_interval: 30m # Or 1h, depending on usage
    scrape_timeout: 60s  # Allow time for the test to complete
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['speedtest.local.kaneworld.org'] # Your exporter's address
        labels:
          instance: 'my-home-internet'
          location: 'Folsom, CA'
          server_name: 'kaneserver.kane.mk:8080'
          # Add other relevant labels (server_id, server_name etc.) [3, 7]

  - job_name: 'CrowdSec MKServer'
    scrape_interval: 30s
    static_configs:
    - targets: ['mkserver.kane.mk:6060']
      labels:
        instance: 'CrowdSec'
        location: 'Folsom, CA'
        machine: 'mkserver.kane.mk'

  - job_name: 'CrowdSec Cyborg'
    scrape_interval: 30s
    static_configs:
    - targets: ['cyborg.kane.mk:6060']
      labels:
        instance: 'CrowdSec'
        location: 'Folsom, CA'
        machine: 'cyborg.kane.mk'

  - job_name: 'CrowdSec Raptor'
    scrape_interval: 30s
    static_configs:
    - targets: ['raptor.kane.mk:6060']
      labels:
        instance: 'CrowdSec'
        location: 'Folsom, CA'
        machine: 'raptor.kane.mk'

  - job_name: 'CrowdSec Auth'
    scrape_interval: 30s
    static_configs:
    - targets: ['auth.kane.mk:6060']
      labels:
        instance: 'CrowdSec'
        location: 'Folsom, CA'
        machine: 'auth.kane.mk'


  - job_name: 'CrowdSec Docker-Ceph'
    scrape_interval: 30s
    static_configs:
    - targets: ['docker-ceph.kane.mk:6060']
      labels:
        instance: 'CrowdSec'
        location: 'Folsom, CA'
        machine: 'docker-ceph.kane.mk'

  - job_name: 'CrowdSec Docker-Dev'
    scrape_interval: 30s
    static_configs:
    - targets: ['docker-dev.kane.mk:6060']
      labels:
        instance: 'CrowdSec'
        location: 'Folsom, CA'
        machine: 'docker-dev.kane.mk'

  - job_name: 'CrowdSec Unraid'
    scrape_interval: 30s
    static_configs:
    - targets: ['kaneserver.kane.mk:6060']
      labels:
        instance: 'CrowdSec'
        location: 'Folsom, CA'
        machine: 'kaneserver.kane.mk'

  - job_name: 'CrowdSec NAS'
    scrape_interval: 30s
    static_configs:
    - targets: ['murdognas.kane.mk:6060']
      labels:
        instance: 'CrowdSec'
        location: 'Folsom, CA'
        machine: 'murdognas.kane.mk'

  # - job_name: 'CrowdSec Pangolin'
  #   scrape_interval: 30s
  #   static_configs:
  #     - targets: ['100.77.15.11:6060']
  #       labels:
  #         instance: 'CrowdSec'
  #         location: 'Oracle VPS'
  #         machine: 'kane-pangolin.kane.mk'
